# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 771, 541))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.title = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.title.setObjectName("title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title)
        self.fire = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fire.setObjectName("fire")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fire)
        self.liquid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.liquid.setObjectName("liquid")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.liquid)
        self.cost = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cost.setObjectName("cost")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cost)
        self.decribtion = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.decribtion.setObjectName("decribtion")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.decribtion)
        self.drubling = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.drubling.setObjectName("drubling")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.drubling)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.error_place = QtWidgets.QLabel(self.formLayoutWidget)
        self.error_place.setText("")
        self.error_place.setObjectName("error_place")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.error_place)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "название сорта"))
        self.label_2.setText(_translate("MainWindow", "степень обжарки"))
        self.label_4.setText(_translate("MainWindow", "молотый/в зернах"))
        self.label_5.setText(_translate("MainWindow", "описание вкуса"))
        self.label_6.setText(_translate("MainWindow", "цена"))
        self.label_7.setText(_translate("MainWindow", "объем упаковки"))
        self.pushButton.setText(_translate("MainWindow", "ГОТОВО"))
